name: Release

on:
  release:
    types: [published]

# Use "trusted publishing", see https://docs.pypi.org/trusted-publishers/
jobs:
  release:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
      - run: pip install build
      - run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          username: __token__
          password: ${{ secrets.PYPI_TOKEN }}
